### PR TITLE
Add BBC17 blog post and pictures

### PR DESCRIPTION
**Pull request by kelnera**
Not sure how the different set up for the BBC website is going to affect the standard rst practices. I'll test that, then tag reviewers.

### CODE REVIEW

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-40.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-40.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-40.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-40.staging.osuosl.org

**Comment by kelnera** [comment]
@osuosl/web-reviewers I think I've got the post to a place that looks good. Some things I've noticed: the align feature doesn't really work as everything is ending up on the left side of the page; featured images do not show up; #32. Other than that, let me know if there are any issues with the post. I'll probably merge this at the end of the day tomorrow as it's already been approved over on the osl site.

**Pull request merged**
