### PR TITLE
Fixed the beaver, removed compass in favor of node-sass, and general cleanup of repo

### PR DESCRIPTION
**Pull request by mmitchellgarcia**
Hey guys - updated the sass compilation step to use node-sass instead of Compass so it's a bit more clear how to compile sass (NPM is in the root of project, instead of that random config.rb file in the css directory). Hopefully this change makes it easier for future devs to build the site.

I also fixed the beaver and removed the .sass-cache files that were checked in on accident.

### CODE REVIEW

**Comment by ramereth** [comment]
@mmitchellgarcia Thanks for the pull request! Is NPM now required to be run on the server hosting the site when pushing updates?

**Comment by mmitchellgarcia** [comment]
@ramereth Nope - NPM is only required in dev, and the script will move the compiled css file into the folder that Pelican builds with. Unfortunately, it's still a two step build, which I'm not happy about, but I had trouble looking for resources on using makefiles to compile sass. Anyone over there done it before?

**Comment by ramereth** [comment]
This LGTM, @Kennric @matthewrsj @lucywyman can you please review?

**Comment by lucywyman** [comment]
Looks good to me as well -- I tested it using the develop server and make html, and both ran without errors and looked fine.

**Comment by Kennric** [comment]
Looks ok to me, too, anything that streamlines the build is nice. Also, thanks for taking out the cache files.  +1

**Pull request merged**
