### PR TITLE
fix 404

### PR DESCRIPTION
**Pull request by jldugger**
If you load up beaverbarcamp.org with developer network tools open, there's a resource requested that 404s:

* http://beaverbarcamp.org/theme/js/ligthbox.min.js

This is a typo that is slowing page loads down by roughly 20 percent. However, fixing the typo causes a fairly ugly lightbox popup on the front page with no content to display. The only page that uses lightbox is the about page comic, and since even that doesn't work as expected, this PR removes the lightbox.min.js reference.

### CODE REVIEW

**Comment by jldugger** [comment]
@osuosl/web-reviewers objections?

**Comment by kelnera** [comment]
For what it's worth, I have no objections.

**Comment by ramereth** [comment]
@jldugger should we go ahead and remove the javascript referenced or just do what you did here?

**Comment by jldugger** [comment]
@ramereth I've gone ahead and removed the associated javascript and map file.

**Comment by ramereth** [comment]
@Kennric can you please make sure that nothing else is using that java script we used and review this please?

**Comment by jldugger** [comment]
Seems pretty straightforward:

    $ ~/src/beaver-barcamp-pelican$ git grep -i lightbox.min.js
    $

**Comment by ramereth** [comment]
@jldugger yes, but is anything referencing the javascript functions it had?

**Comment by jldugger** [comment]
Ah, well, you're talking about a minified javascript, so good luck auditing that. At the very least, production is clearly running without it.

**Comment by jldugger** [comment]
And FWIW, I don't get any errors in the javascript console while browsing a devserver running this branch.

**Pull request merged**
