### PR TITLE
Add video from EECS youtube

### PR DESCRIPTION
**Pull request by khashf**
- Embed [youtube video from EECS channel](https://www.youtube.com/watch?v=2Bh9HyCo9Ik) to the About page
- Add a link on the front page referring the About page

### CODE REVIEW

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-51.staging.osuosl.org

**Comment by khashf** [comment]
[Add BarCamp video to Pelican](https://trello.com/c/7V8QEgWA/1270-add-barcamp-video-to-pelican)

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-51.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://beaver-barcamp-pelican-51.staging.osuosl.org

**Pull request merged**
